swagger: "2.0"

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: "1.1"
  title: Operational Real-time APIs
# during dev, should point to your local machine
host: "/"
# basePath prefixes all resource paths
basePath: /operations/api/account
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json

################################################################################
#                                           Paths                              #
################################################################################
paths:
  /{accountID}/queuehealth:
    get:
      description: Retrieving Queue Health Data by Account and Skills
      parameters:
        - name: accountID
          in: path
          description: 'Account Id'
          required: true
          type: string
          format: ^[a-zA-Z0-9_]{1,20}$
        - name: timeframe
          in: query
          description: > 
           The time range (in minutes) by which the data can be filtered. 
           Where end time is the current time and the start time  = end time - timeframe. 
           The maximum timeframe value is 1440 (24 hours).
          required: true
          type: integer
        - name: v
          in: query
          description: 'Version of API. e.g. v=1'
          required: true
          type: integer
        - name: skillIds
          in: query
          description: >
           When provided, metrics on the response will be grouped by the requested skills. 
           When not provided, metrics on the response will be calculated at the account level. 
           You can provide one or more skillIDs, Example: skillIds=4,15,3. 
           To retrieve all skills active for the time period, use skillIds=all.
          required: false
          type: string
        - name: interval
          in: query
          description: >
           Interval size in minutes. 
           When provided, the returned data will be aggregated by intervals of the requested size. 
           The interval has to be smaller or equal to the time frame and also a divisor of the time frame. 
           Example: 
           timeframe=60&interval=30 (correct) 
           timeframe=60&interval=61 (bad request) 
           timeframe=60&interval=31 (bad request)
          required: false
          type: integer
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Queuehealth'

################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  Queuehealth:
    type: object
    properties:
      skillsMetrics:
        type: array
        items:
          $ref: '#/definitions/SkillMetric'
  SkillMetric:
    type: object
    properties:
      name:
        type: String
