swagger: "2.0"

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: "1.1"
  title: Agent Manager APIs
# during dev, should point to your local machine
host: "/"
# basePath prefixes all resource paths
basePath: /1.1
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json

################################################################################
#                                           Paths                              #
################################################################################
paths:
  /operations/api/account/{accountID}/queuehealth:
    get:
      description: Retrieving Queue Health Data by Account and Skills
      parameters:
        - name: accountID
          in: path
          description: 'Account Id'
          required: true
          type: string
          format: ^[a-zA-Z0-9_]{1,20}$
        - name: timeframe
          in: query
          description: 'The time range (in minutes) by which the data can be filtered. Where: end time is the current time and the start time  = end time - timeframe. The maximum timeframe value is 1440'
          required: true
          type: integer
        - name: skillIds
          in: query
          description: 'When provided, metrics on the response will be grouped by the requested skills. When not provided, metrics on the response will be calculated at the account level. You can provide one or more skill IDs. For example: skillIds=4,15,3 . To retrieve all skills active for the time period use skillIds=all, comma seperated integers'
          required: false
          type: string
        - name: interval
          in: query
          description: 'Interval size in minutes. When provided, the returned data will be aggregated by intervals of the requested size. The interval has to be smaller or equal to the time frame and also a divisor of the time frame. For example: timeframe=60&interval=30 (correct), timeframe=60&interval=61 (bad request), timeframe=60&interval=31 (bad request)'
          required: false
          type: integer
        - name: trim_user
          in: query
          description: 'When set to either true, t or 1, each tweet returned in a timeline will include a user object'
          required: false
          type: string
        - name: v
          in: query
          description: 'Version of API. e.g. v=1'
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Tweets'

################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  Tweets:
    type: object
    properties:
      contributors:
        type: array
        items:
          $ref: '#/definitions/Contributors'
      coordinates:
        $ref: '#/definitions/Coordinates'
      created_at:
        type: string
      current_user_retweet:
        $ref: '#/definitions/Tweets'
      entities:
        $ref: '#/definitions/Entities'
      favorite_count:
        type: integer
      favorited:
        type: boolean
      filter_level:
        type: string
      id:
        type: integer
      id_str:
        type: string
      in_reply_to_screen_name:
        type: string
      in_reply_to_status_id:
        type: integer
      in_reply_to_status_id_str:
        type: string
      in_reply_to_user_id:
        type: integer
      in_reply_to_user_id_str:
        type: string
      lang:
        type: string
      place:
        $ref: '#/definitions/Places'
      possibly_sensitive:
        type: boolean
      quoted_status_id:
        type: integer
      quoted_status_id_str:
        type: string
      quoted_status:
        $ref: '#/definitions/Tweets'
      scopes:
        type: object
        additionalProperties: {}
      retweet_count:
        type: integer
      retweeted:
        type: boolean
      retweeted_status:
        $ref: '#/definitions/Tweets'
      source:
        type: string
      text:
        type: string
      truncated:
        type: string
      user:
        $ref: '#/definitions/Users'
      withheld_copyright:
        type: boolean
      withheld_countries:
        type: array
        items:
          type: string
      withheld_scope:
        type: string
